# Generated by Django 2.0 on 2020-01-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsAndNetworksInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('models_name', models.CharField(max_length=500)),
                ('common_path', models.CharField(max_length=500)),
                ('models_path', models.CharField(max_length=500)),
                ('models_size', models.CharField(max_length=500)),
                ('networks_path', models.CharField(max_length=500)),
                ('total_params', models.CharField(max_length=255)),
                ('flops', models.CharField(max_length=255)),
                ('flops_result_info', models.CharField(max_length=5000)),
                ('flops_result', models.CharField(default='脚本未执行', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
