# Generated by Django 2.0 on 2020-01-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkDetailInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('build_id', models.CharField(max_length=500)),
                ('apk_name', models.CharField(max_length=500)),
                ('apk_type', models.CharField(max_length=50)),
                ('apk_location', models.CharField(max_length=500)),
                ('test_result', models.CharField(default='未测试', max_length=32)),
                ('test_desc', models.CharField(max_length=5000)),
                ('market_desc', models.CharField(max_length=5000)),
                ('pull_request_items', models.CharField(max_length=1000)),
                ('is_tab', models.CharField(default='0', max_length=2)),
                ('is_report', models.CharField(default='0', max_length=2)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApkReportDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apk_id', models.IntegerField()),
                ('test_report_name', models.CharField(max_length=255)),
                ('test_report_data', models.BinaryField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pull_request_id', models.IntegerField(default=0)),
                ('build_id', models.CharField(max_length=255)),
                ('apk_type', models.CharField(max_length=50)),
                ('commit_msg', models.CharField(max_length=1000)),
                ('jenkins_info_full_str', models.CharField(max_length=5000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_sign_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequestInfo',
            fields=[
                ('pull_request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=50)),
                ('complete_time', models.DateTimeField()),
            ],
        ),
    ]
