# Generated by Django 2.0 on 2020-01-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_phone_package_manager_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequestinfo',
            name='complete_time',
            field=models.DateTimeField(null=True),
        ),
    ]
